name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        run: |
          docker-compose run \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            -e BASE_API_URL=${{ secrets.BASE_API_URL }} \
            -e STUDENT_EMAIL=${{ secrets.STUDENT_EMAIL }} \
            -e STUDENT_PASSWORD=${{ secrets.STUDENT_PASSWORD }} \
            -e STUDENT_FIRST_NAME=${{ secrets.STUDENT_FIRST_NAME }} \
            -e STUDENT_LAST_NAME=${{ secrets.STUDENT_LAST_NAME }} \
            -e TUTOR_EMAIL=${{ secrets.TUTOR_EMAIL }} \
            -e TUTOR_PASSWORD=${{ secrets.TUTOR_PASSWORD }} \
            -e TUTOR_FIRST_NAME=${{ secrets.TUTOR_FIRST_NAME }} \
            -e TUTOR_LAST_NAME=${{ secrets.TUTOR_LAST_NAME }} \
            -e API_KEY_FOR_EMAILS=${{ secrets.API_KEY_FOR_EMAILS }} \
            spaceto_study /bin/sh -c "docker-compose up --exit-code-from spaceto_study || true"

      - name: Generate Allure report
        run: |
          sudo docker-compose run spaceto_study /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
